services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siapnikah_frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Uncomment the line below if you want to load environment variables from a .env file
    # env_file:
    #   - .env
